export interface iDetalleFactura{
    IdVentaDetalle :string;
    IdVenta: string;
    Index:number;
    IdProducto:number;
    Codigo: string;
    Producto: string;
    IdUnidad : number;
    IdImpuesto : any;
    TasaCambio : number;
    Existencia : number;
    Precio: number;
    PrecioCordoba: number;
    PrecioDolar: number;
    PorcDescuento: number;
    PorcDescuentoAdicional: number;
    PorcImpuesto: number;
    Cantidad: number;
    SubTotal:number;
    SubTotalCordoba:number;
    SubTotalDolar:number;
    Descuento:number;
    DescuentoCordoba:number;
    DescuentoDolar:number;
    DescuentoAdicional:number;
    DescuentoAdicionalCordoba:number;
    DescuentoAdicionalDolar:number;
    SubTotalNeto:number;
    SubTotalNetoCordoba:number;
    SubTotalNetoDolar:number;
    Impuesto:number;
    ImpuestoCordoba:number;
    ImpuestoDolar:number;
    ImpuestoExo:number;
    ImpuestoExoCordoba:number;
    ImpuestoExoDolar:number;
    Total:number;
    TotalCordoba:number;
    TotalDolar:number;
    EsBonif : boolean;
    EsBonifLibre : boolean;
    EsLibInvEscasan : boolean;
    EsExonerado : boolean;
    EsExento : boolean;
    PrecioLiberado : boolean;
    Margen : number;
    PedirAutorizado: boolean;
    Autorizado: boolean;
    UsuarioAutoriza: string,
    IndexUnion : number;
    IdPrecioFAC :number;
    IdEscala :number;
    IdDescuentoDet :number;
    IdLiberacion : number;
    IdLiberacionBonif : number;
    FacturaNegativo :boolean;
    Lotificado:number;
}