export interface iFichaCliente{
    Codigo : string;
    Cliente: string;
    Ruc : string;
    Correo: string;
    Plazo: any;
    Telefono: string;
    Direccion : string;
    Moneda: string;
    Limite: any;
    Disponible: number;
    SaldoDolar : number;
    SaldoCordoba : number;
    UltimoRoc : number;
    UltimoRocFecha: Date;
    UltimoRocMonto : number;
    UltimoRocMoneda : string;
    MonedaSistema : string;
    MonedaLocal : string;
    IdConceptoPrecio: any;
    CodVendedor: any;
    CuentaClave: boolean;
    SuspendidoMoroso: boolean;
    ConfianzaFactSiempre: boolean;
    ConfianzaFactVencido: boolean;
    ConfianzaFactUnaVez: boolean;
    Estado: string;
    Bodegas: string[];
    Usuario: string;
}